name: Rust

on: [push]

jobs:
  build-life-lib:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - working-directory: life-lib
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
